name: Test

on:
  pull_request:
  push:
    tags:
      - '!**'
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34.1
      - name: Test
        run: make go/test

